import { spawn } from "node:child_process";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const apiDir = process.env.TILDE_API_DIR ?? resolve(root, "../tilde-api");
const source =
  process.env.TILDE_OPENAPI_PATH ?? resolve(apiDir, "openapi.cloud.json");
const rootSpecTarget = resolve(root, "openapi.cloud.json");
const specTarget = resolve(root, "specs/openapi.cloud.json");
const typeTarget = resolve(root, "packages/core/src/generated/schema.d.ts");

await mkdir(dirname(rootSpecTarget), { recursive: true });
await mkdir(dirname(specTarget), { recursive: true });
await mkdir(dirname(typeTarget), { recursive: true });
await copyFile(source, rootSpecTarget);
await copyFile(source, specTarget);

await run("pnpm", ["exec", "openapi-ts"]);

await run("pnpm", [
  "exec",
  "openapi-typescript",
  "specs/openapi.cloud.json",
  "-o",
  "packages/core/src/generated/schema.d.ts",
]);

const generated = await readFile(typeTarget, "utf8");
const header = `// This file is generated by \`pnpm sync:openapi\`.
// Source: ${source}
// Do not edit manually.

`;
await writeFile(
  typeTarget,
  header + generated.replace(/^\/\*\*[\s\S]*?\*\/\n?/, ""),
);

console.log(`Synced OpenAPI from ${source}`);

function run(command: string, args: string[]): Promise<void> {
  return new Promise((resolveRun, reject) => {
    const child = spawn(command, args, {
      cwd: root,
      stdio: "inherit",
      shell: false,
    });
    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) {
        resolveRun();
      } else {
        reject(new Error(`${command} ${args.join(" ")} exited with ${code}`));
      }
    });
  });
}
